baseURL = "https://andreasvijensen.github.io/"
languageCode = "en-us"
title = "Andreas Videbæk Jensen"
theme = "PaperMod"
enableRobotsTXT = true

[params]
  description = "Assistant Professor of Political Science"
  author = "Andreas Videbæk Jensen"
  defaultTheme = "auto"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  showToc = false

  [params.profileMode]
    enabled = false

  [params.homeInfoParams]
    Title = "Andreas Videbæk Jensen"
    Content = """
<img class=\"home-photo\" src=\"/img/profile.jpg\" alt=\"Andreas Videbæk Jensen\">

Assistant Professor of Political Science at Aarhus University. My research examines how education shapes political participation and democratic attitudes, using quantitative methods and computational tools.

Email: <a href=\"mailto:avj@ps.au.dk\">avj@ps.au.dk</a>
"""

[menu]
  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 20

  [[menu.main]]
    identifier = "teaching"
    name = "Teaching"
    url = "/teaching/"
    weight = 30

  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv/"
    weight = 40
